### ISSUE TITLE
Error: Cannot find module 'vue-loader'

### ISSUE THREAD

**Issue by subaru-hello** [subaru-hello/wellbe_corp#18]
### Error Log
Here is the Error.
```ruby
internal/modules/cjs/loader.js:818
11:43:17 webpacker.1 |   throw err;
11:43:17 webpacker.1 |   ^
11:43:17 webpacker.1 | 
11:43:17 webpacker.1 | Error: Cannot find module 'vue-loader'
11:43:17 webpacker.1 | Require stack:
11:43:17 webpacker.1 | - /Users/subaru/Portfolio/welbe_corp/config/webpack/environment.js
11:43:17 webpacker.1 | - /Users/subaru/Portfolio/welbe_corp/config/webpack/development.js
11:43:17 webpacker.1 | - /Users/subaru/Portfolio/welbe_corp/node_modules/webpack-cli/bin/utils/convert-argv.js
11:43:17 webpacker.1 | - /Users/subaru/Portfolio/welbe_corp/node_modules/webpack-dev-server/bin/webpack-dev-server.js
11:43:17 webpacker.1 |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
11:43:17 webpacker.1 |     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
11:43:17 webpacker.1 |     at Module.require (internal/modules/cjs/loader.js:887:19)
11:43:17 webpacker.1 |     at require (internal/modules/cjs/helpers.js:74:18)
11:43:17 webpacker.1 |     at Object.<anonymous> (/Users/subaru/Portfolio/welbe_corp/config/webpack/environment.js:2:29)
11:43:17 webpacker.1 |     at Module._compile (internal/modules/cjs/loader.js:999:30)
11:43:17 webpacker.1 |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
11:43:17 webpacker.1 |     at Module.load (internal/modules/cjs/loader.js:863:32)
11:43:17 webpacker.1 |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
11:43:17 webpacker.1 |     at Module.require (internal/modules/cjs/loader.js:887:19) {
11:43:17 webpacker.1 |   code: 'MODULE_NOT_FOUND',
11:43:17 webpacker.1 |   requireStack: [
11:43:17 webpacker.1 |     '/Users/subaru/Portfolio/welbe_corp/config/webpack/environment.js',
11:43:17 webpacker.1 |     '/Users/subaru/Portfolio/welbe_corp/config/webpack/development.js',
11:43:17 webpacker.1 |     '/Users/subaru/Portfolio/welbe_corp/node_modules/webpack-cli/bin/utils/convert-argv.js',
11:43:17 webpacker.1 |     '/Users/subaru/Portfolio/welbe_corp/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
11:43:17 webpacker.1 |   ]
11:43:17 webpacker.1 | }
11:43:18 webpacker.1 | exited with code 1
11:43:18 system      | sending SIGTERM to all processes
11:43:18 css.1       | rails aborted!
11:43:18 css.1       | SignalException: SIGTERM
11:43:18 css.1       | /Users/subaru/Portfolio/welbe_corp/config/application.rb:22:in `<main>'
11:43:18 css.1       | /Users/subaru/Portfolio/welbe_corp/Rakefile:6:in `require_relative'
11:43:18 css.1       | /Users/subaru/Portfolio/welbe_corp/Rakefile:6:in `<main>'
11:43:18 css.1       | /Users/subaru/Portfolio/welbe_corp/bin/rails:7:in `<top (required)>'
11:43:18 css.1       | /Users/subaru/Portfolio/welbe_corp/bin/spring:12:in `require'
11:43:18 css.1       | /Users/subaru/Portfolio/welbe_corp/bin/spring:12:in `block in <top (required)>'
11:43:18 css.1       | <internal:kernel>:90:in `tap'
11:43:18 css.1       | /Users/subaru/Portfolio/welbe_corp/bin/spring:9:in `<top (required)>'
11:43:18 css.1       | bin/rails:4:in `load'
11:43:18 css.1       | bin/rails:4:in `<main>'
11:43:18 css.1       | (See full trace by running task with --trace)
11:43:18 css.1       | exited with code 1
11:43:18 web.1       | terminated by SIGTERM
```
I have no idea what to do about this error,  tried to reinstall vue-cli  though.
I thought it is derived from vueLoaderPlugin below.
```ruby
/config/webpack/environment.js
const { environment } = require('@rails/webpacker')
const { VueLoaderPlugin } = require('vue-loader')
const vue = require('./loaders/vue')

environment.plugins.prepend('VueLoaderPlugin', new VueLoaderPlugin())
environment.loaders.prepend('vue', vue)
module.exports = environment
```
develop environment
- ruby 3.0.0
- vue 3 ver.
- rails 6v
- mysql2

**Comment by subaru-hello** [comment]
### Successed way to Resolve
I was silly to have forgotten to install vue-loader to my app. Only type command below in you CLI, then vue-loader will be installed to your package.json
```ruby
rails webpacker:install:vue
```
